workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean
      - name: Set iOS deployment target
        script: |
          cd ios
          sed -i '' 's/^#*\s*platform\s*:ios.*$/platform :ios, '\''13.0'\''/' Podfile
          if ! grep -q "platform :ios, '13.0'" Podfile; then
            echo "platform :ios, '13.0'" >> Podfile
          fi
          pod install --repo-update
          cd ..
      - name: Build iOS app
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
