workflows:
  ios:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: 1.16.2
    scripts:
      # 1. Ensure Flutter dependencies are up-to-date
      - flutter pub get

      # 2. Clean previous build artifacts
      - flutter clean

      # 3. Remove existing 'ios' directory (optional, ensure you have backups)
      - rm -rf ios

      # 4. Recreate 'ios' directory with necessary files
      - flutter create --platforms=ios .

      # 5. Navigate to 'ios' directory and install CocoaPods dependencies
      - cd ios && pod install

      # 6. Return to the root directory
      - cd ..

      # 7. Build the iOS app with Flutter, without code signing for CI/CD
      - flutter build ios --release --no-codesign
