workflows:
  ios:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: 1.16.2
    scripts:
      # 1. Ensure Flutter dependencies are up-to-date
      - flutter pub get

      # 2. Clean previous build artifacts
      - flutter clean

      # 3. Navigate to 'ios' directory
      - cd ios

      # 4. Check if 'Podfile' exists; if not, create one with the appropriate platform version
      - |
        if [ ! -f Podfile ]; then
          cat <<EOF > Podfile
          platform :ios, '13.0'

          target 'Runner' do
            use_frameworks!
            use_modular_headers!

            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end
          EOF
        else
          echo "Podfile already exists. Skipping creation."
        fi

      # 5. Install CocoaPods dependencies
      - pod install

      # 6. Return to the root directory
      - cd ..

      # 7. Build the iOS app with Flutter, without code signing for CI/CD
      - flutter build ios --release --no-codesign
