workflows:
  ios:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: 1.16.2
    scripts:
      # 1. Ensure Flutter dependencies are up-to-date
      - name: Flutter Pub Get
        script: flutter pub get

      # 2. Clean previous build artifacts
      - name: Flutter Clean
        script: flutter clean

      # 3. Navigate to 'ios' directory
      - name: Navigate to iOS Directory
        script: cd ios

      # 4. Initialize Podfile and set platform to iOS 13
      - name: Initialize and Configure Podfile
        script: |
          if [ ! -f Podfile ]; then
            pod init
            sed -i '' 's/# platform: :ios, '.*'/platform :ios, '13.0'/g' Podfile
          fi

      # 5. Clean iOS build artifacts and install CocoaPods dependencies
      - name: Clean and Install Pods
        script: |
          rm -rf build Pods Podfile.lock
          rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
          pod cache clean --all
          arch -x86_64 pod install --repo-update

      # 6. Return to the root directory
      - name: Return to Root Directory
        script: cd ..

      # 7. Build the iOS app with Flutter, without code signing for CI/CD
      - name: Build iOS App
        script: flutter build ios --release --no-codesign

