workflows:
  ios:
    name: Flutter iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.2
      cocoapods: 1.16.2
    scripts:
      # 1. Ensure Flutter dependencies are up-to-date
      - name: Flutter Pub Get
        script: flutter pub get

      # 2. Clean previous build artifacts
      - name: Flutter Clean
        script: flutter clean

      # 3. Navigate to 'ios' directory
      - name: Navigate to iOS Directory
        script: cd ios

      # 4. Remove existing build artifacts, Pods, and cache
      - name: Clean iOS Build Artifacts and Cache
        script: |
          rm -rf build Pods Podfile.lock
          rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
          pod cache clean --all

      # 5. Install CocoaPods dependencies with x86_64 architecture
      - name: Install CocoaPods Dependencies
        script: arch -x86_64 pod install --repo-update

      # 6. Return to the root directory
      - name: Return to Root Directory
        script: cd ..

      # 7. Build the iOS app with Flutter, without code signing for CI/CD
      - name: Build iOS App
        script: flutter build ios --release --no-codesign
